server:
  port: 8085
  shutdown: graceful
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 20s
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: config-server
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    config:
      server:
        git:
          # указываем ссылку на Git репозиторий, в котором хранятся конфигурационные файлы
          uri: https://github.com/alex-java-tutor/config-repository
          # по умолчанию сервер будет получать данные с ветки main, в нашем репозитории основная ветка - master.
          default-label: master
          timeout: 5
          # По умолчанию сервер клонирует репозиторий при первом запросе от клиентов на
          # получение конфигураций. Данный параметр говорит серверу склонировать репозиторий
          # при старте приложения. Во-первых, это ускоряет ответ на запрос клиента, а
          # во-вторых, это позволяет серверу быстрее упасть, в случае ошибки связи с
          # репозиторием - проблему лучше выяснить на старте, чем во время работы
          # микросервисов.
          clone-on-start: true
          # После клонирования удаленного репозитория сервер использует его локальную версию.
          # Этот параметр, выставленный в true, говорит серверу всегда пулить изменения из
          # удаленного репозитория, чтобы данные были максимально актуальными.
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health
